services:
  my-db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pwd1234
      MYSQL_DATABASE: mydb
    ports:
      - 3306:3306

  my-cache-server-1:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  # my-cache-server-2:
  #   container_name: redis2
  #   image: redis
  #   ports:
  #     - 6380:6380

  # my-cache-server-3:
  #   container_name: redis3
  #   image: redis
  #   ports:
  #     - 6381:6381
