name: Deploy To EC2 (Self-hosted)

on:
  push:
    branches:
      - 'CI/CD-Test'

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:

      - name: Pull latest code
        run: |
          cd /home/ubuntu/barojobBackend
          git pull origin CI/CD-Test    # 새 브랜치 내용 반영


      - name: Clean application.yml
        run: rm -f /home/ubuntu/barojobBackend/src/main/resources/application.yml

      - name: Apply application.yml from secret
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        run: |
          echo "$APPLICATION_PROPERTIES" > /home/ubuntu/barojobBackend/src/main/resources/application.yml


      - name: Build JAR with Gradle
        run: |
          cd /home/ubuntu/barojobBackend
          chmod +x gradlew                  
          ./gradlew clean build -x test     


      - name: Build Docker image
        run: |
          cd /home/ubuntu/barojobBackend
          sudo docker build -t barojob-backend:latest .


      - name: Stop and remove previous container
        run: |
          if sudo docker ps -q -f name=barojob-backend >/dev/null; then
            sudo docker stop barojob-backend
            sudo docker rm   barojob-backend
          fi


      - name: Run new container
        run: |
          sudo docker run -d \
            --name barojob-backend \
            -p 8080:8080 \          
            --restart unless-stopped \
            barojob-backend:latest