name: Deploy To EC2 (Self-hosted)

on:
  push:
    branches:
      - CI/CD-Test

jobs:
  deploy:
    runs-on: [self-hosted, linux]  

    env:
      APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clean application.yml
        run: rm -f src/main/resources/application.yml

      - name: Apply application.yml from secret
        run: echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml

      - name: Switch to CI/CD-Test branch
        run: |
          if git show-ref --verify --quiet refs/heads/CI/CD-Test; then
            git checkout CI/CD-Test
            git pull origin CI/CD-Test
          else
            git fetch origin CI/CD-Test:CI/CD-Test
            git checkout CI/CD-Test
          fi

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Kill existing application
        run: sudo fuser -k -n tcp 8080 || true

      - name: Run application
        run: nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &