name: Deploy To EC2 (Self-hosted)

on:
  push:
    branches:
      - CI/CD-Test

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          clean: true

      - name: Ensure latest code
        run: |
          git fetch origin ${{ github.ref_name }}
          git reset --hard origin/${{ github.ref_name }}
          git clean -ffdx

      - name: Clean application.yml
        run: rm -f src/main/resources/application.yml

      - name: Apply application.yml from secret
        run: echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml

      - name: Build with Gradle
        run: ./gradlew clean build
        working-directory: /home/ubuntu/barojobBackend

      - name: Copy jar to service path
        run: cp build/libs/server-*.jar /home/ubuntu/barojobBackend/build/libs/server-0.0.1-SNAPSHOT.jar
        working-directory: /home/ubuntu/barojobBackend

      - name: Reload systemd daemon
        run: sudo systemctl daemon-reload

      - name: Restart barojob service
        run: sudo systemctl restart barojob.service

      - name: Check service status
        run: sudo systemctl status barojob.service --no-pager