name: Deploy To EC2 (Self-hosted)

on:
  push:
    branches:
      - 'CI/CD-Test'

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Pull latest code
        run: |
          cd /home/ubuntu/barojobBackend
          git fetch origin CI/CD-Test
          git reset --hard origin/CI/CD-Test

      - name: Clean application.yml
        run: rm -f /home/ubuntu/barojobBackend/src/main/resources/application.yml

      - name: Apply application.yml from secret
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        run: |
          echo "$APPLICATION_PROPERTIES" > /home/ubuntu/barojobBackend/src/main/resources/application.yml

      - name: Build JAR with Gradle
        run: |
          cd /home/ubuntu/barojobBackend
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Build Docker image
        run: |
          cd /home/ubuntu/barojobBackend
          sudo docker build -t barojob-backend:latest .

      - name: Create Docker network if not exists
        run: |
          sudo docker network create barojob-net || true

      - name: Stop and remove previous app container if exists
        run: |
          CONTAINER_ID=$(sudo docker ps -aq -f name=barojob-backend)
          if [ -n "$CONTAINER_ID" ]; then
            sudo docker stop "$CONTAINER_ID"
            sudo docker rm   "$CONTAINER_ID"
          else
            echo "기존 앱 컨테이너가 없습니다."
          fi

      - name: Start Redis container
        run: |
          sudo docker pull redis:latest
          EXIST=$(sudo docker ps -aq -f name=redis-local)
          if [ -n "$EXIST" ]; then
            sudo docker stop redis-local
            sudo docker rm   redis-local
          fi
          sudo docker run -d \
            --name redis-local \
            --network barojob-net \
            -p 6379:6379 \
            --restart unless-stopped \
            redis:latest

      - name: Run new app container
        run: |
          sudo docker rm -f barojob-backend || true
          sudo docker run -d \
            --name barojob-backend \
            --network barojob-net \
            -p 8080:8080 \
            --restart unless-stopped \
            barojob-backend:latest

      - name: Run Node Exporter
        run: |
          # 기존 컨테이너가 있으면 제거
          sudo docker rm -f node-exporter || true
          # host 네트워크로 실행해야 호스트 OS 메트릭 수집 가능
          sudo docker run -d \
            --name node-exporter \
            --network host \
            --restart unless-stopped \
            prom/node-exporter:latest