name: Deploy To EC2 (Self-hosted)

on:
  push:
    branches:
      - 'CI/CD-Test'

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: 'CI/CD-Test'
          fetch-depth: 0
          clean: true

      - name: Clean application.yml
        run: rm -f src/main/resources/application.yml

      - name: Apply application.yml from secret
        run: echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml

      - name: Reload systemd daemon
        run: sudo systemctl daemon-reload

      - name: Restart barojob service
        run: sudo systemctl restart barojob.service

      - name: Check service status
        run: sudo systemctl status barojob.service --no-pager