name: Deploy To EC2 (Self-hosted)

on:
  push:
    branches:
      - 'CI/CD-Test'

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Pull latest code
        run: |
          cd /home/ubuntu/barojobBackend
          git fetch --all
          git reset --hard origin/CI\/CD-Test

      - name: Clean application.yml
        run: rm -f src/main/resources/application.yml

      - name: Apply application.yml from secret
        run: echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml

      - name: Reload systemd daemon
        run: sudo systemctl daemon-reload

      - name: Restart barojob service
        run: sudo systemctl restart barojob.service

      - name: Check service status
        run: sudo systemctl status barojob.service --no-pager